---

  - name: install slideatlas dependencies
    apt: name={{ item }} state=present
    sudo: yes
    with_items:
      - libpng12-dev
      - libfreetype6-dev
      - libxft-dev
      - subversion-tools
      - python-numpy

  - name: install specified python requirements
    pip: requirements=/vagrant/requirements.txt
    sudo: yes
